import byc from './byc-logo.png';
import vector from './vector.png';
import heart from './heart-icon.png';
import cart from './shopping-cart.png';
import user from './user-profile.png';
import pay from './payments.png';
import phone from './vector (2).png';
import mail from './mail.png';
import fb from './facebook.png';
import insta from './instagra.png';
import twi from './x.png';
import yt from './youtube.png';
import fleft from './first-left.png';
import fmid from './first-middle.png';
import fright from './first-right.png';
import sleft from './sleft.png';
import smid from './smid.png';
import sright from './sright.png'
import ttr from './ttright.png'
import tbl from './tbleft.png'
import tbr from './tbright.png'
import arrowleft from './arrow-left.png'
import arrowright from './arrow-right.png'
import pic1 from './aleftpic.png'
import pic2 from './amidpic.png'
import pic3 from './arightpic.png'
import lastl from './lleft.png'
import lastm from './lmid.png'
import lastr from './lright.png'
import lpic from './yellow.png'
import eye from './views.png'
import lasth from './likes.png'
import larrow from './arrow.png'
import bfirst from './blogfirst.png'
import bsecond from './blogsecond.png'
import bfoot from './blogfoot.png'
import b3 from './blog3.png'
import blog2 from './blog2.png'
import apic1 from './aboutpic1.png'
import apic2 from './aboutpic2.png'
import apic11 from './aboutpic11.png'
import firstimg from './bycfirst.png'
import footarrow from './arrow-footer.png'
import lcard from './little-card.png'
import recent from './byc-woman.png'
import redvec from './redvector.png'
import star from './4.5.png'
import address from './add.png'
import phn from './phn.png'
import maile from './em.png'
import conta from './mapp.png'
import bxs1 from './boxers1.png'
import bxs2 from './boxers2.png'
import bxs3 from './boxers3.png'
import bxs4 from './boxers4.png'
import bxs5 from './boxers5.png'
import wishlove from './lovebtn.png'
import wishcart from './cartbtn.png'
import cboxer from './cartboxer.png'
import cplus from './cartplus.png'
import cartdel from './cartdelete.png'
import checkpay from './coutpay.png'
import round1 from './round1.png'
import round2 from './round2.png'
import mrater from './mratings.png'
import marrowl from './modaleft.png'
import marrowr from './modaright.png'
import mboxers from './modboxers.png'
import mboxer from './modboxer.png'
import mnum from './modnum.png'
import mplus from './modplus.png'
import msize from './modsizes.png'
import mrange from './modrange.png'
import mstar1 from './modstar1.png'
import mstar2 from './modstar2.png'
import mcart from './modcart.png'
import snav from './serchnav.png'

export{byc, mnum, mplus, msize, mstar1, snav, mstar2, bxs1, mrater, mrange, marrowl, marrowr, mboxers, mboxer,  checkpay, round1, round2, bxs2, wishlove, cboxer, cplus, cartdel, wishcart, bxs3, bxs4, bxs5, vector, heart, cart, user, pay, phone, mail, fb, insta, twi, yt, fleft,fmid, fright, sleft, smid, sright, ttr, tbl, tbr,
     arrowleft, footarrow, recent, redvec, lcard, arrowright, pic1, pic2, pic3, lastl, firstimg, lastm, lastr, apic11, lpic, eye, lasth,
      larrow, bfirst, bsecond, address, mcart, phn, maile, conta, star, bfoot, b3, blog2, apic1, apic2}